# Generated by Django 5.1.6 on 2025-02-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='student_model',
        ),
    ]
