# Generated by Django 5.1.6 on 2025-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0002_rename_student_student_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coursename", models.CharField(max_length=100)),
            ],
        ),
    ]
