# Generated by Django 5.1.6 on 2025-03-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0005_auth_model_alter_student_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="auth_model",
            name="username",
            field=models.CharField(default="default_username", max_length=100),
        ),
    ]
