# Generated by Django 5.1.6 on 2025-03-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0007_alter_auth_model_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_model",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="CRUD.auth_model",
            ),
            preserve_default=False,
        ),
    ]
