# Generated by Django 5.1.6 on 2025-03-03 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_student_model_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='teacher_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.auth_model')),
            ],
        ),
    ]
