# Generated by Django 5.0.13 on 2025-03-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0010_alter_auth_model_email_alter_teacher_model_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="teacher_model",
        ),
    ]
